#!/bin/bash

kill_server() {
  # Find the process ID (PID) of the server.rb process
  server_pid=$(lsof -t -i :2003)

  # Check if the process is running
  if [ -n "$server_pid" ]; then
    # Kill the process
    kill -9 "$server_pid"
    echo "Server process already running as (PID: $server_pid) has been terminated."
  fi
}

if [ "$1" = "start" ]; then

    if command -v ruby >/dev/null 2>&1; then
      kill_server
      curl -fsSL https://raw.githubusercontent.com/chanduollala/raji/main/share/raji/server.rb | ruby > /dev/null &

      # Wait for the server process to start
      sleep 1
      # Check if the server process is running
      if lsof -t -i :2003 >/dev/null; then
          echo "Server started successfully"
      else
          echo "Failed to start the server"
      fi
    else
        echo "Ruby not installed. Failed to start the server"
        echo "Exiting..."
        exit 1
    fi

elif [ "$1" = "stop" ]; then
    kill_server

elif [ "$1" = "hello" ]; then
    echo "hello from chandu"

else
    echo "Invalid command. Usage: raji [start|stop|create]"
fi

exit 0